site_name: Droptools
repo_name: droptools
repo_url: https://github.com/benjamin-bader/droptools
site_url: https://droptools.bendb.com
site_description: "Useful Dropwizard addons"
site_author: Benjamin Bader

copyright: "Copyright &copy; 2014-2019 Benjamin Bader"

theme:
  name: material
  logo: "images/logo.png"
  favicon: "images/favicon.ico"
  palette:
    primary: indigo
    accent: lime

markdown_extensions:
  - smarty
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - tables

nav:
  - "Overview": index.md
  - "jOOQ": jooq.md
  - "Redis": redis.md

